USE [25410333_GISDB];
GO

-- Bảng quản lý đối tượng ĐIỂM (Points)
CREATE TABLE FEATURE_POINT (
    IDP INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    LOCATION NVARCHAR(255),
    CATEGORY NVARCHAR(50),
    LONG FLOAT NOT NULL,
    LAT FLOAT NOT NULL
);

-- Bảng quản lý đối tượng ĐƯỜNG / TUYẾN (Polylines)
CREATE TABLE FEATURE_LINE (
    IDL INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    LOCATION NVARCHAR(255)
);

-- Bảng lưu danh sách chuỗi tọa độ kết nối ĐƯỜNG (Có STT)
CREATE TABLE LINE_POINT (
    IDL INT,
    STT INT,
    LONG FLOAT NOT NULL,
    LAT FLOAT NOT NULL,
    PRIMARY KEY (IDL, STT),
    FOREIGN KEY (IDL) REFERENCES FEATURE_LINE(IDL) ON DELETE CASCADE
);

-- Bảng quản lý đối tượng ĐA GIÁC / VÙNG (Polygons)
CREATE TABLE FEATURE_POLYGON (
    IDPO INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    LOCATION NVARCHAR(255)
);

-- Bảng lưu danh sách tọa độ khép kín tạo ĐA GIÁC (Có STT)
CREATE TABLE POLY_POINT (
    IDPO INT,
    STT INT,
    LONG FLOAT NOT NULL,
    LAT FLOAT NOT NULL,
    PRIMARY KEY (IDPO, STT),
    FOREIGN KEY (IDPO) REFERENCES FEATURE_POLYGON(IDPO) ON DELETE CASCADE
);
GO